### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by Gsimken** [RecklessBoon/Macro-Deck-Streamlabs-OBS-Plugin#3]
The plugin its not getting the scenes or change some status. is it outdated?

**Comment by F-luxus** [comment]
Hello,
Is it planning to fix it? 
Streamlabs not connecting at all. streamlabs are using API TOKEN and this part is missing from this plugin. 
Maybe older versions works without it. But now its not, saddly 😢

**Comment by RecklessBoon** [comment]
Can you provide logs? Last time I updated and tested this it was working. Sorry I didn't get to this earlier.

**Comment by Andyyy41** [comment]
Hi @RecklessBoon , 

Old thread, I know, but having the same issue here.  Thought I'd post in case you're still working on this plugin.

As soon as you select:
- Switch Scene Selection
- Switch Scene
- Mute/Unmute Audio Source
- Set Audio Source Volume/Deflection
- Update Scene Item Settings

**Switch Scene**
17:21:26 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Object reference not set to an instance of an object.
   at RecklessBoon.MacroDeck.Streamlabs_OBS_Plugin.UI.Controls.SwitchSceneActionConfigurator..ctor(SwitchSceneAction action, ActionConfigurator actionConfigurator) in /home/runner/work/Macro-Deck-Extensions/Macro-Deck-Extensions/Plugins/RecklessBoon.MacroDeck.StreamlabsOBSPlugin/UI/Controls/SwitchSceneActionConfigurator.cs:line 26
   at RecklessBoon.MacroDeck.Streamlabs_OBS_Plugin.Actions.SwitchSceneAction.GetActionConfigControl(ActionConfigurator actionConfigurator) in /home/runner/work/Macro-Deck-Extensions/Macro-Deck-Extensions/Plugins/RecklessBoon.MacroDeck.StreamlabsOBSPlugin/Actions/SwitchSceneAction.cs:line 31
   at SuchByte.MacroDeck.GUI.ActionConfigurator.ActionConfiguratorActionItem_MouseClick(Object sender, MouseEventArgs e) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\Dialogs\ActionConfigurator.cs:line 139
   at SuchByte.MacroDeck.GUI.CustomControls.ActionConfiguratorActionItem.Control_MouseClick(Object sender, MouseEventArgs e) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\CustomControls\ActionConfiguratorActionItem.cs:line 24
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Switch Collection**
16:15:06 [Macro Deck] [Error] >> MacroDeck: ApplicationThreadException: Object reference not set to an instance of an object.
   at RecklessBoon.MacroDeck.Streamlabs_OBS_Plugin.UI.Controls.SwitchCollectionActionConfigurator..ctor(SwitchCollectionAction action, ActionConfigurator actionConfigurator) in /home/runner/work/Macro-Deck-Extensions/Macro-Deck-Extensions/Plugins/RecklessBoon.MacroDeck.StreamlabsOBSPlugin/UI/Controls/SwitchCollectionActionConfigurator.cs:line 26
   at RecklessBoon.MacroDeck.Streamlabs_OBS_Plugin.Actions.SwitchCollectionAction.GetActionConfigControl(ActionConfigurator actionConfigurator) in /home/runner/work/Macro-Deck-Extensions/Macro-Deck-Extensions/Plugins/RecklessBoon.MacroDeck.StreamlabsOBSPlugin/Actions/SwitchCollectionAction.cs:line 32
   at SuchByte.MacroDeck.GUI.ActionConfigurator.ActionConfiguratorActionItem_MouseClick(Object sender, MouseEventArgs e) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\Dialogs\ActionConfigurator.cs:line 139
   at SuchByte.MacroDeck.GUI.CustomControls.ActionConfiguratorActionItem.Control_MouseClick(Object sender, MouseEventArgs e) in D:\a\Macro-Deck\Macro-Deck\MacroDeck\GUI\CustomControls\ActionConfiguratorActionItem.cs:line 24
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Label.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, MessageId msg, WPARAM wparam, LPARAM lparam)

**Comment by Willem1981** [comment]
Will this be fixed?

**Comment by Andyyy41** [comment]
> Will this be fixed?

As a work around, I made buttons with keyboard commands and assigned hotkeys to the scenes etc in Slobs.  Works as expected, just a shame this integration doesn't.
